organization:
  class: "http://xmlns.com/foaf/0.1/Organization"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#downloadLocation"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  overview: "http://vivoweb.org/ontology/core#overview"
  offersDegree:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    field: "http://vivoweb.org/ontology/core#majorField"
  abbreviation: "http://vivoweb.org/ontology/core#abbreviation"
  date: "http://vivoweb.org/ontology/core#dateTime"
  sponsorsAwardOrHonor: "http://www.w3.org/2000/01/rdf-schema#label"
  awardOrHonorGiven: "http://www.w3.org/2000/01/rdf-schema#label"
  awardOrHonorReceived: "http://www.w3.org/2000/01/rdf-schema#label"
  keyword: "http://vivoweb.org/ontology/core#freetextKeyword"
  organizationForTraining: "http://vivoweb.org/ontology/core#majorField"
  people:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    title: "http://vivoweb.org/ontology/core#hrJobTitle"
  hasSubOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  organizationWithin: "http://www.w3.org/2000/01/rdf-schema#label"
  leadOrganizationOf: "http://www.w3.org/2000/01/rdf-schema#label"
  hasCollaboratingOrganizatgionOrGroup: "http://www.w3.org/2000/01/rdf-schema#label"
  hasAffiliatedOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  memberOf: ""
  clinicalActivity: ""
  convenerOfEvent: ""
  attendedEvent: ""
  selectedPublication: ""
  publisherOf: ""
  presentation: ""
  featuredIn: ""
  assigneeForPatent: ""
  translatorOf: ""
  awardsGrant: ""
  administersGrant: ""
  subcontractsGrant: ""
  performsHumanStudy: ""
  contractOrProviderForService: ""
  outreachAndCommunityServiceActivity: ""
  hasEquipment: ""
  offersCourse: ""
  orgId: "http://vivo.library.tamu.edu/ontology/TAMU#OrgID"
  sameAs: ""
  phone: ""
  fax: ""
  emailAddress: "http://www.w3.org/2006/vcard/ns#email"
  address:
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    region: "http://www.w3.org/2006/vcard/ns#region"
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    country: "http://www.w3.org/2006/vcard/ns#country"
  geographicLocation: "http://www.w3.org/2006/vcard/ns#geo"
  locatedAtFacility: ""
  predecessorOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  successorOrganization: "http://www.w3.org/2000/01/rdf-schema#label"
  governingAuthorityFor: ""
  hasResearchArea: "http://www.w3.org/2000/01/rdf-schema#label"
