concept:
  class: "http://www.w3.org/2004/02/skos/core#Concept"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#downloadLocation"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  researchAreaOf:
    person: "http://www.w3.org/2000/01/rdf-schema#label"
    title: "http://vivoweb.org/ontology/core#hrJobTitle"
  organization: "http://www.w3.org/2000/01/rdf-schema#label"