person:
  class: "http://xmlns.com/foaf/0.1/Person"
  name: "http://www.w3.org/2000/01/rdf-schema#label"
  type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  image: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  thumbnail: "http://vitro.mannlib.cornell.edu/ns/vitro/public#directDownloadUrl"
  primaryEmail: "http://www.w3.org/2006/vcard/ns#email"
  additionalEmail: "http://www.w3.org/2006/vcard/ns#email"
  phone: "http://www.w3.org/2006/vcard/ns#telephone"
  website:
    url: "http://www.w3.org/2006/vcard/ns#url"
    label: "http://www.w3.org/2000/01/rdf-schema#label"
  orcidId: "http://vivoweb.org/ontology/core#orcidId"
  preferredTitle: "http://www.w3.org/2000/01/rdf-schema#label"
  position:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
  overview: "http://vivoweb.org/ontology/core#overview"
  researchArea: "http://www.w3.org/2000/01/rdf-schema#label"
  geographicFocus:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  hrJobTitle: "http://vivoweb.org/ontology/core#hrJobTitle"
  keyword: "http://www.w3.org/2000/01/rdf-schema#label"
  headOf: "http://www.w3.org/2000/01/rdf-schema#label"
  memberOf: "http://www.w3.org/2000/01/rdf-schema#label"
  hasCollaborator: "http://www.w3.org/2000/01/rdf-schema#label"
  clinicalActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  attendedEvent: "http://www.w3.org/2000/01/rdf-schema#label"
  educationAndTraining:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    organization: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  credentials: "http://www.w3.org/2000/01/rdf-schema#label"
  credentialEligibilityAttained: "http://www.w3.org/2000/01/rdf-schema#label"
  awardsAndHonors:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  adviseeOf: "http://www.w3.org/2000/01/rdf-schema#label"
  selectedPublication:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  collectionOrSeriesEditorFor:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  editorOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  presentation:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    event: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  featuredIn:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  assigneeForPatent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  translatorOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  researchOverview: "http://vivoweb.org/ontology/core#researchOverview"
  principalInvestigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  coPrincipalInvestigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  investigatorOn:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    awardedBy: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  otherResearchActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  teachingOverview: "http://vivoweb.org/ontology/core#teachingOverview"
  teachingActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  advisee: "http://www.w3.org/2000/01/rdf-schema#label"
  outreachOverview: "http://vivoweb.org/ontology/core#outreachOverview"
  reviewerOf:
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
    date: "http://vivoweb.org/ontology/core#dateTime"
  contactOrProvidorForService: "http://www.w3.org/2000/01/rdf-schema#label"
  organizerOfEvent:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  professionalServiceActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  outreachAndCommunityServiceActivity: "http://www.w3.org/2000/01/rdf-schema#label"
  performsTechnique: "http://www.w3.org/2000/01/rdf-schema#label"
  hasExpertiseInTechnique: "http://www.w3.org/2000/01/rdf-schema#label"
  isni: "http://vivo.library.tamu.edu/ontology/TAMU#ISNI"
  netid: "http://vivo.library.tamu.edu/ontology/TAMU#NETID"
  researcherId: "http://vivo.library.tamu.edu/ontology/TAMU#ResearcherId"
  twitter: "http://vivo.library.tamu.edu/ontology/TAMU#twitterId"
  uid: "http://vivo.library.tamu.edu/ontology/TAMU#UID"
  uin: "http://vivo.library.tamu.edu/ontology/TAMU#UIN"
  youtube: "http://vivo.library.tamu.edu/ontology/TAMU#youtube"
  sameAs:
    label: "http://www.w3.org/2000/01/rdf-schema#label"
    type: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#mostSpecificType"
  eRACommonsId: "http://vivoweb.org/ontology/core#eRACommonsId"
  isiResearcherId: "http://vivoweb.org/ontology/core#researcherId"
  scopusId: "http://vivoweb.org/ontology/core#scopusId"
  healthCareProviderId: "http://www.w3.org/2000/01/rdf-schema#label"
  email: "http://www.w3.org/2006/vcard/ns#email"
  firstName: "http://www.w3.org/2006/vcard/ns#givenName"
  middleName: "http://www.w3.org/2006/vcard/ns#middleName"
  lastName: "http://www.w3.org/2006/vcard/ns#familyName"
  fullName: "http://www.w3.org/2000/01/rdf-schema#label"
  address:
    streetAddress: "http://www.w3.org/2006/vcard/ns#streetAddress"
    locality: "http://www.w3.org/2006/vcard/ns#locality"
    region: "http://www.w3.org/2006/vcard/ns#region"
    postalCode: "http://www.w3.org/2006/vcard/ns#postalCode"
    country: "http://www.w3.org/2006/vcard/ns#country"
  geographicLocation: "http://www.w3.org/2000/01/rdf-schema#label"
  locatedInFacility: "http://www.w3.org/2000/01/rdf-schema#label"
  fax: "http://www.w3.org/2006/vcard/ns#fax"
  etdChairOf:
    name: "http://www.w3.org/2000/01/rdf-schema#label"
    title: "http://www.w3.org/2000/01/rdf-schema#label"
    date: "http://vivoweb.org/ontology/core#dateTime"
  modTime: "http://vitro.mannlib.cornell.edu/ns/vitro/0.7#modTime"
